### ISSUE TITLE
Idea: Notify when it detects an Absolute JumP, that can be optimized for Relative Jump (JR)

### ISSUE THREAD

**Issue by mvac7** [Fubukimaru/asMSX#36]
When the JP instruction is used and the difference between the direction of the jump instruction with respect to the address of the Label is less than + -128, then notify the output, which can be optimized using a Relative Jump instruction.

**Comment by Fubukimaru** [comment]
This is quite interesting. I would propose to have a flag in the application that enables this kind of warning message.

Something like:
```
asmsx -w code.asm
```

Prints
```
Warning: Line XX can be optimized changing using relative jump as the jump address is close
```

Of course, it is not a priority at the moment because some internals of the code must be modified before (to enable this and fix other bugs). But I would like to keep this in mind.

**Comment by theNestruo** [comment]
**About this specific issue:**

This is quite interesting indeed. However I thinks there should be two different flags:

- `-wsize` or `-info-jr` to warn about JP that could be JR (saving 1 byte)
- `-wspeed` or `-info-jp` to warn about JR that could be JP (saving 2 t-states)

My main concern is related to what should happen with conditional jumps (JR could be 2 t-states slower if the branch is taken or 3 faster otherwise).
And another question is that some parts of the code should prefer saving bytes (initialization), and some other parts should prefer speed (game loop)...

Another useful notification happens in the sequence `call somewhere / ret`, that usually can be replaced by the faster and sorter `jp somewhere`.

**About the info/warning system in general:**

_(maybe this should be a different issue. Also, I don't know the internals of asmsx, so probably I'm asking for flying unicorns!)_

A _one-size-fits-all_ approach could be generate these warnings as "info" (instead of warning) and using a "negative approach" (info is shown by default unless filtered out), so the flags will be used to remove that info from the actual output (e.g.: `-no-info-jp`).

As a bonus point, this "negative approach" could be extended to special markers comments. This comments would decorate the actual code to filter out already considered optimizations to avoid noise in the output (e.g.: `jp somewhere ; no-info-jr ; Faster!`).

**Comment by oboroc** [comment]
I like the idea, but I want to use consistent flags, or may be no flags at all. Until @Fubukimaru added "-z", there were no flags. Just directives in asm files.

**Comment by Fubukimaru** [comment]
I would like to have a set of flags available so that you don't have to put weird things in the code just for that.

I have a new flag working on NOP_Revision branch (-v and -vv), which are meant for verbose output.  Maybe we can work towards a consistent list of names for flags.

By the way, now -z works properly as the zilog variable is going to be defined in asmsx.h as global state. In the future we may want to pass these kind of values in a struct to all the functions for unit testing purposes.

What do you think?

**Comment by Fubukimaru** [comment]
https://github.com/santiontanon/mdlz80optimizer/issues/23

MDLZ80Optimizer already does this!

```
Hi Fubukimaru, definitively! mdl should already do this, given the right flags. For example, if you would want mdl to let you know of all jp that can be turned into jr, you just have to add this flag to the command line: "-po size".

MDL's current optimizer is a pattern-based optimizer. It reads patterns from a file and applies them. By default (with "-po") it uses a file ( https://github.com/santiontanon/mdlz80optimizer/blob/master/src/main/resources/data/pbo-patterns.txt ) with patterns that optimize ensuring BOTH size and speed benefits. You can specify your own pattern file (-po "filename"), or use the "-po size" or "-po speed" flags to use alternative files that optimize focusing on size or focusing on speed. The "-po size" file includes patterns for jp->jr optimizations :)
```

Let's use this amazing optimizer :). Closing this!

**Comment by oboroc** [comment]
Agree, before adding new features, it's better to get current features working well
