### ISSUE TITLE
[theNestruo] "Add NOPs random" bug

### ISSUE THREAD

**Issue by ghost** [Fubukimaru/asMSX#4]
From: https://github.com/Libertium/asmsx-license-gpl/issues/2
________________________________________
What steps will reproduce the problem?
1. Add/Modify code.
2. Add/Modify labels.

What is the expected output? What do you see instead?
Compile without errors.
Syntax errors, unidentified labels, unexpected errors.

What version of the product are you using? On what operating system?
asmsx012e. Windows XP SP3.

Please provide any additional information below.
I think this is a very old bug commented in this thread
http://karoshi.auic.es/index.php?PHPSESSID=431a55f2ec0476ce4469934d2b2dd3e1&topi
c=472.0
It is nonsense that occurs with some frequency. It is not important but very 
annoying.

**Comment by Fubukimaru** [comment]
There is no evidence that this bug is due to preprocessors as ~tmpre files only differ in the commented line (Line appears or not).

**Comment by Fubukimaru** [comment]
It seems that it mistakes symbols (EQU) with labels somehow. Probably the problem is in the grammar.

**Comment by theNestruo** [comment]
Hi!
In case it helps isolating the root cuase, I found that placing the random NOPs in the ROM header, between _.dw INIT_ and the _.org rom_start + $10_ ([example](https://github.com/theNestruo/msx-wrally/blob/master/src/rally.asm#L339)):

- is enough to remove/reproduce the problem (once it has already appeared)
- has no effect in the final binary (those bytes are $00 in any case)

Maybe it is a good scenario to determine the root cause (as all the labels will have the same values, etc. so there are less variations involved)...

Good luck with this bug!

**Comment by Fubukimaru** [comment]
Thanks for the info!

I hope we find it :)

**Comment by Fubukimaru** [comment]
I have found a couple of things:

- It doesn't really need to be a NOP to fix it. Any instruction would do.
- It doesn't really need to be a new instruction, you can modify current ones
     + For example: or 11111b may crash but changing it to or 1111111b can fix it.
- In my current code to reproduce NOP bug (sorry, it cannot be public as it was lent to me to fix this with this condition) the problem is that the tag is never registered, so it should be a problem with the grammar (OH NOES).

If it's a special case of the grammar or the tokenizer it may be hard to locate it. Eventually we'll reach that point ;).

**Comment by Fubukimaru** [comment]
New finding by @jamque:

When you have a code that gives you the NOP bug. If you rename the main code file it may assemble.

This points to the length of the temporal files. The text processing gets broken at some point.

**Comment by Fubukimaru** [comment]
On the private file aaaaaaaa.asm we find that one label is not defined. The log says the following when it should be registering the label:
```
Registering label: ine 661 - on pass 1
```

This `ine 661` comes from other place and overwrites the original `ROOM11`. Probably there is an overflow on some vector.

A more complete log on this (adding flex/bison output):
```
Reducing stack by rule 2 (line 277):
   $1 = nterm start ()
   $2 = nterm line ()
-> $$ = nterm start ()
Entering state 1
Stack now 0 1
Reading a token
--accepting rule at line 417 ("ROOM11")
Next token is token IDENTIFICATOR ()
Shifting token IDENTIFICATOR ()
Entering state 3
Stack now 0 1 3
Reading a token
--(end of buffer or a NUL)
--accepting rule at line 429 (":")
Next token is token ':' ()
Shifting token ':' ()
Entering state 129
Stack now 0 1 3 129
Reducing stack by rule 19 (line 314):
   $1 = token IDENTIFICATOR ()
   $2 = token ':' ()
Registering label: ine 661 - on pass 1
```
The grammar gets the `ROOM11` but it somehow gets overriden.

I'll get back when I can do more tests.
