### ISSUE TITLE
asmsx variables are unsigned short int type

### ISSUE THREAD

**Issue by jamque** [Fubukimaru/asMSX#82]
CODE:
```
VALUE = 60000
PRINT VALUE
VALUE = VALUE + 10000
PRINT VALUE
```
OUTPUT in txt file:
```
60000
4464
```
LOL!
It looks like asmsx variables are unsigned short int type, 16 bits.
Could be unsigned int type? 32 bits ? OR maybe this will collided with some features to use them with assembly opcodes?

**Comment by Fubukimaru** [comment]
In dura.y:
```
	| PSEUDO_PRINT value
	{
		if (conditional[conditional_level])
		{
			if (pass == 2)
			{
				if (fmsg == NULL)
					create_txt();
				if (fmsg)
					fprintf(fmsg, "%d\n", (short int)$2 & 0xffff);
			}
		}
	}
```
For some reason there is a truncation on `PSEUDO_PRINT` when there is a value. I believe that this is of wrong nature as it leads to print something that is not actually happening. I believe that this would be done because of the truncation available for `value_16bits` for example. But it shouldn't be managed in the print function.

As it only affects printing, I'm changing the fprintf line.

**Comment by jamque** [comment]
I has seen in line 706 of dura.y file, that has the same behavior as PSEUDO_PRINT for HEX print values. And uses dot as separator as a float number. I don't understand why. Could you revise please and fix that HEX print to be more that 65536?

**Comment by Fubukimaru** [comment]
Done.

I have also changed PRINTFIX:

```
fprintf(fmsg, "%.4f\n", (float)($2 / 256));
```

I assume that the `/ 256` is because of the internal formatting of floats in assembler.
